services:
  dashjs:
    image: clarkzjw/dashjs:tomm24
    build:
      context: .
      dockerfile: Dockerfile-dashjs
    ports:
      - "3000"
    restart: always

  nginx:
    image: clarkzjw/dashjs-nginx:tomm24
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
    restart: always

  livesim2:
    image: clarkzjw/dashjs-livesim2:tomm24
    build:
      context: .
      dockerfile: Dockerfile-livesim2
    ports:
      - 8888:8888
    restart: always
