FROM --platform=$BUILDPLATFORM nginx:1.27.2
ARG TARGETPLATFORM
ARG BUILDPLATFORM

# No interactive frontend during docker build
ENV DEBIAN_FRONTEND=noninteractive \
    DEBCONF_NONINTERACTIVE_SEEN=true

RUN apt-get update && apt-get install vim net-tools iputils-ping iproute2 python3 supervisor iperf3 build-essential \
                                      sudo git irtt procps htop tcpdump make \
                                      python3-pip python3-venv python3-pandas python3-dev \
                                      iperf3 wget curl -y

WORKDIR /opt/bin/

WORKDIR /etc/nginx

COPY etc/nginx/conf.d/livesim2.conf /etc/nginx/conf.d/default.conf
COPY shaper/supervisord.conf /etc/supervisor/supervisord.conf

COPY shaper/entrypoint.sh /opt/bin/
COPY shaper/tc.py /opt/bin/tc.py
COPY shaper/*.csv /opt/bin/

RUN  mkdir -p /var/run/supervisor /var/log/supervisor && chmod +x /opt/bin/entrypoint.sh

ENV PYTHONUNBUFFERED=1

WORKDIR /opt/bin/

ENTRYPOINT ["/opt/bin/entrypoint.sh"]
CMD ["/opt/bin/entrypoint.sh"]

# docker run --rm --privileged -it --entrypoint=/bin/bash clarkzjw/dashjs-nginx-ebpf