FROM --platform=$BUILDPLATFORM node:20.17.0
ARG TARGETPLATFORM
ARG BUILDPLATFORM

RUN apt-get update && apt-get install iputils-ping net-tools -y

ADD https://api.github.com/repos/clarkzjw/dash.js/git/refs/heads/tomm24 version.json

RUN git clone -b tomm24 --depth 1 https://github.com/clarkzjw/dash.js.git

WORKDIR dash.js

RUN npm install

CMD ["npm", "run", "start"]
