FROM --platform=$BUILDPLATFORM golang:1.23.3 AS builder
ARG TARGETPLATFORM
ARG BUILDPLATFORM

WORKDIR /usr/src/app

ADD https://api.github.com/repos/clarkzjw/livesim2/git/refs/heads/dev version.json

RUN git clone https://github.com/Dash-Industry-Forum/livesim2.git

WORKDIR /usr/src/app/livesim2

RUN git checkout v1.6.0 && go mod download && go mod tidy && go mod verify

RUN make build && cd cmd/cmaf-ingest-receiver && go build

RUN ls -alh /usr/src/app/livesim2/out/

FROM --platform=$BUILDPLATFORM ubuntu:24.04 AS downloader
ARG TARGETPLATFORM
ARG BUILDPLATFORM

WORKDIR /livesim2

RUN apt-get update && apt-get install -y ca-certificates wget unzip iperf3 tree

COPY --from=builder /usr/src/app/livesim2/out/ /livesim2/

# RUN ./dashfetcher -a
                    # test content from https://cta-wave.github.io/Test-Content/
                    #    croatia
                    #    https://dash.akamaized.net/WAVE/vectors/switching_sets/12.5_25_50/ss1/2023-10-05/stream.mpd

                    #    tos
                    #    https://dash.akamaized.net/WAVE/vectors/switching_sets/15_30_60/ss1/2023-10-05/stream.mpd

                    # datasets at AAU.at dataset are not compatible with livesim2
                    # https://ftp.itec.aau.at/datasets/DASHDataset2014/BigBuckBunny/1sec/BigBuckBunny_1s_simple_2014_05_09.mpd
                    # https://ftp.itec.aau.at/datasets/DASHDataset2014/BigBuckBunny/2sec/BigBuckBunny_2s_simple_2014_05_09.mpd

RUN wget https://starlink-dash-live.jinwei.me/tos.zip && unzip tos.zip && rm tos.zip
RUN wget https://starlink-dash-live.jinwei.me/croatia.zip && unzip croatia.zip && rm croatia.zip

RUN cd /livesim2/tos/WAVE/vectors && \
    mv cfhd_sets chdf_sets switching_sets/15_30_60/ss1/2023-10-05 && \
    cd switching_sets/15_30_60/ss1/2023-10-05 && \
    sed -i -e 's/..\/..\/..\/..\///g' stream.mpd && \
    cd /livesim2/croatia/WAVE/vectors && \
    mv cfhd_sets chdf_sets switching_sets/12.5_25_50/ss1/2023-10-05/ && \
    cd switching_sets/12.5_25_50/ss1/2023-10-05/ && \
    sed -i -e 's/..\/..\/..\/..\///g' stream.mpd

EXPOSE 8888

CMD ["./livesim2", "--vodroot=/livesim2"]

# http://ip:8888/livesim2/tos/WAVE/vectors/switching_sets/15_30_60/ss1/2023-10-05/stream.mpd
# http://ip:8888/livesim2/croatia/WAVE/vectors/switching_sets/12.5_25_50/ss1/2023-10-05/stream.mpd
